CREATE TABLE users_body_composition (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_arm DECIMAL,
    right_arm DECIMAL,
    chest DECIMAL,
    waist DECIMAL,
    hips DECIMAL,
    left_thigh DECIMAL,
    right_thigh DECIMAL,
    left_calf DECIMAL,
    right_calf DECIMAL,
    weight DECIMAL NOT NULL,
    body_fat DECIMAL,
    date_created timestamp DEFAULT now() NOT NULL,
    date_updated timestamp,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL

)