CREATE TYPE body_category as ENUM ('lower body','upper body');

CREATE TABLE body_part (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    category body_category not NULL,
    date_created timestamp DEFAULT now ()
)