CREATE TABLE muscle_group (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    body_part_id INTEGER REFERENCES body_part(id) ON DELETE SET NULL,
    date_created timestamp DEFAULT NOW ()
)