CREATE TABLE workouts_exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER REFERENCES workouts(id) ON DELETE CASCADE NOT NULL,
    exercise_id INTEGER REFERENCES exercises(id) ON DELETE CASCADE NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    UNIQUE(workout_id,exercise_id)
)